using Npgsql;
using NpgsqlTypes;

namespace StoreWeb.Api.Services;

internal static class DataProtectionKeyTableInitializer
{
    private const long DatabaseInitializationLockId = 0x53544F5245574542L;

    public static async Task EnsureCreatedAsync(
        string connectionString,
        CancellationToken cancellationToken = default
    )
    {
        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync(cancellationToken);
        await using var transaction =
            await connection.BeginTransactionAsync(cancellationToken);

        await using (var lockCommand = new NpgsqlCommand(
            "SELECT pg_advisory_xact_lock(@lockId);",
            connection,
            transaction
        ))
        {
            lockCommand.Parameters.Add("lockId", NpgsqlDbType.Bigint).Value =
                DatabaseInitializationLockId;
            await lockCommand.ExecuteNonQueryAsync(cancellationToken);
        }

        const string sql = """
            CREATE TABLE IF NOT EXISTS "DataProtectionKeys" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                "FriendlyName" TEXT,
                "Xml" TEXT,
                CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
            );
            """;

        await using var command = new NpgsqlCommand(sql, connection, transaction);
        await command.ExecuteNonQueryAsync(cancellationToken);
        await transaction.CommitAsync(cancellationToken);
    }
}
